config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts'
  resources :groups
  resources :questions, only: [:index, :create_right_answer, :create_wrong_answer]
  resources :users, only: :index
  
  root 'static_pages#index'
  get '/static_pages', to: 'static_pages#index'
  get '/groups/:id/join_group', to: 'groups#add_user'
  post '/questions/:id/create_right_answer', to: 'questions#create_right_answer'
  post '/questions/:id/create_wrong_answer', to: 'questions#create_wrong_answer'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	validates :user_id, :question_id, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :groups_users, dependent: :destroy
	has_many :users, through: :groups_users 

	validates_presence_of :name
end

app/models/groups_user.rb
class GroupsUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
	validates_presence_of :user_id, :group_id
end

app/models/question.rb
class Question < ActiveRecord::Base
	validates_presence_of :body
	has_many :answers
	has_many :users, through: :answers

	def self.random_question
		question = Question.all.sample
		tweeters = Tweeter.all.sort_by{rand}
		first = tweeters[0]
		second = tweeters[1]
		return {question: question, first: first, second: second}
	end
end

app/models/tweeter.rb
class Tweeter < ActiveRecord::Base
	validates :name, :username, presence: true

	def update_attributes
		set_twitter_api
		self.followers_count = @twitter.user(self.username).followers_count
		self.creation_date = @twitter.user(self.username).created_at
		self.friends_count = @twitter.user(self.username).friends_count
		self.statuses_count = @twitter.user(self.username).statuses_count
		self.save
	end

	private
	def set_twitter_api
		@twitter = Twitter::REST::Client.new do |config|
		  config.consumer_key = ENV['twitter_consumer_key']
		  config.consumer_secret = ENV['twitter_consumer_secret_key']
		  config.access_token = ENV['twitter_access_token']
		  config.access_token_secret = ENV['twitter_secret_access_token']
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups_users, dependent: :destroy
  has_many :groups, through: :groups_users
  has_many :answers
  has_many :questions, through: :answers

  def score
  	self.answers.select{ |answer| answer.is_correct? == true }.count
  end

  def self.all_user_scores
    users = User.all.sort_by{ |user| user.score }.reverse
    a = []
    users.each do |u|
      a << {
        email: u.email,
        score: u.score
      }
    end
    return a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_group, except: [:index, :new, :create]

	def index
		@groups = Group.all
		@group = Group.new
	end

	def add_user
		if current_user.groups.include?(@group)
			redirect_to @group
		else
			@groups_user = GroupsUser.create(user_id: current_user.id, group_id: params[:id], is_owner?: false)
		end
	end

	def show
		@group_users = @group.users.sort_by{ |user| user.score }.reverse
		@topscore = @group_users[0]
		respond_to do |format|
			format.html
			format.json {render json: @group_users}
		end
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			@groups_user = GroupsUser.create(user_id: current_user.id, group_id: @group.id, is_owner?: true)
			redirect_to @group
		else
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def set_group 
		@group = Group.find(params[:id])
	end

	def group_params
		params.require(:group).permit(:name)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@random_question = Question.random_question
		respond_to do |format|
			format.html
			format.json {render json: @random_question}
		end
	end

	def create_right_answer
		@answer = Answer.create(user_id: current_user.id, question_id: params[:id], is_correct?: true)
		redirect_to_index_after_answer
	end

	def create_wrong_answer
		@answer = Answer.create(user_id: current_user.id, question_id: params[:id], is_correct?: false)
		redirect_to_index_after_answer
	end

	private
	def redirect_to_index_after_answer
		if @answer.save
			redirect_to questions_path
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	# before_action :authenticate_user!

	def index
		@users = User.all.sort_by{ |user| user.score }.reverse[0,5]
		@topscore = @users[0]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all_user_scores[0,5]
		respond_to do |format|
			format.html
			format.json {render json: @users}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<div>
	<%= form_for @group do |f| %>
	<p>	<%= f.label :name %></p>
	<p>	<%= f.text_field :name %></p>
	<br>
	<%= f.submit :class => 'button' %> 
	<% end %>
</div>

app/views/groups/index.html.erb
<div class = "groupbox">
	

	<h2>Groups</h2>
	<!-- <div class = "groupboxtext"> -->
	<table>
	<% @groups.each do |g| %>
		<tr>
			<th><%= g.name %></th> 
			<th><%= link_to 'Join group', '/groups/' + g.id.to_s + '/join_group', :class => "button", :id => "joingroup" %></th>
			<th class='line'> | </th>
			<th><%= link_to 'See scoreboard', group_path(g), :class => "button", :id => "seescoreboard" %></th>
		</tr>	
	<% end %>
	</table>
		<h3>New Group</h3>
		<%= render 'form' %>
	
	<!-- </div> -->

</div>

app/views/groups/new.html.erb
<div class = "groupbox">
	<h3>New Group</h3>
	<%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class='scoreboardBox'>
	<h2><%= @group.name %></h2>
  <ul class='scoreboard'>
    <% @group_users.each do |u| %>
    <li>
      <p><%= u.email %></p>
      <p>Score: <%= u.score %></p>
      <div class="bar-wrap"><span class="bar-fill" style="width: <%= (u.score.to_f / @topscore.score) * 100 %>%;"></span></div>
    </li>
  <% end %>
  <li><%= link_to 'Back', groups_path%></li>

  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterquiz</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1>Pointless Twitter Game</h1>
		<% if current_user %>
			<nav>
				<ul>
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'Groups', groups_path %></li>
					<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
				</ul>
			</nav>
		<% else %>
			<nav>
				<ul>
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'Log in', new_user_session_path %></li>
					<li><%= link_to 'Sign up', new_user_registration_path %></li>
				</ul>
			</nav>
		<% end %>
	</header>

<%= yield %>
	<footer>
		View the code on <a href='https://github.com/andrewsunglaekim/twitter_game'>GitHub</a>
	</footer>
</body>
</html>

app/views/static_pages/_quiz.html.erb
<div class='quiz' style='display:none'>
	<a id='quit' href='#'>x</a>
	<p class='question'></p>
	<ul>
	  <li class='answer'></li>
	  <li class='answer'></li>
	</ul>
	<button id='next' style='display:none'>Next</button>
</div>

<script type="text/javascript">
	updateScoreboard();
</script>

app/views/static_pages/_score.html.erb
<div class="scoreboardBox">
  <ul class='scoreboard'>
    <% @users.each do |u| %>
    <li>
      <p><%= u.email %></p>
      <p>Score: <%= u.score %></p>
      <div class="bar-wrap"><span class="bar-fill" style="width: <%= (u.score.to_f / @topscore.score) * 100 %>%;"></span></div>
    </li>
  <% end %>
  </ul>
</div>

app/views/static_pages/index.html.erb
<div class='container'>
  <button id='start'>Start!</button>
  <%= render 'quiz' %>
  <%= render 'score' %>
</div>


<% if current_user %>
  <p class='user' id='<%= current_user.id %>'></p>
<% end %>

<script type="text/javascript">
$('#start').on('click', function(event){
	event.preventDefault();
	$(this).hide();
	$('.quiz').show();
});

$('#quit').on('click', function(event){
	event.preventDefault();
	$('.quiz').hide();
  $('#start').show();
})
</script>